spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scratch-app?autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

# App Properties
scratch-app:
  jwtSecret: iAppSecretKey
  jwtExpirationMs: 86400000

